### ISSUE TITLE
Can't install ext4 version

### ISSUE THREAD

**Issue by Sogl** [vivid-planet/kwf-app-demo#1] opened 2015-02-04 06:33 UTC
Hi!

I tried to install ext4 version of this app on my WAMP and got an error on build step:

```
c:\OpenServer\domains\kwfapp>php bootstrap.php build
[ 1/3] building trl...... OK (2ms)
[ 2/3] building events... OK (387ms)
[ 3/3] building assets...
calculating dependencies...
 42% [#########------------] Admin js                                          e
xception 'Kwf_Exception' with message 'Can't resolve dependency: require ext.Sup
port' in C:\OpenServer\domains\kwfapp\vendor\koala-framework\kwf-extjs\Kwf\Ext\A
ssets\Provider.php:131
Stack trace:
#0 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asset
s\ProviderList\Abstract.php(114): Kwf_Ext_Assets_Provider->getDependenciesForDep
endency(Object(Kwf_Ext_Assets_JsDependency))
#1 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asset
s\ProviderList\Abstract.php(104): Kwf_Assets_ProviderList_Abstract->getDependenc
iesForDependency(Object(Kwf_Ext_Assets_JsDependency))
#2 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asset
s\ProviderList\Abstract.php(86): Kwf_Assets_ProviderList_Abstract->_setDependenc
iesForDependency(Object(Kwf_Ext_Assets_JsDependency))
#3 C:\OpenServer\domains\kwfapp\vendor\koala-framework\kwf-extjs\Kwf\Ext\Assets\
Provider.php(191): Kwf_Assets_ProviderList_Abstract->findDependency('Ext4.util.D
elay...')
#4 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asset
s\ProviderList\Abstract.php(114): Kwf_Ext_Assets_Provider->getDependenciesForDep
endency(Object(Kwf_Ext_Assets_JsDependency))
#5 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asset
s\ProviderList\Abstract.php(104): Kwf_Assets_ProviderList_Abstract->getDependenc
iesForDependency(Object(Kwf_Ext_Assets_JsDependency))
#6 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asset
s\ProviderList\Abstract.php(86): Kwf_Assets_ProviderList_Abstract->_setDependenc
iesForDependency(Object(Kwf_Ext_Assets_JsDependency))
#7 C:\OpenServer\domains\kwfapp\vendor\koala-framework\kwf-extjs\Kwf\Ext\Assets\
Provider.php(191): Kwf_Assets_ProviderList_Abstract->findDependency('Ext4.util.E
vent')
#8 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asset
s\ProviderList\Abstract.php(114): Kwf_Ext_Assets_Provider->getDependenciesForDep
endency(Object(Kwf_Ext_Assets_JsDependency))
#9 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asset
s\ProviderList\Abstract.php(104): Kwf_Assets_ProviderList_Abstract->getDependenc
iesForDependency(Object(Kwf_Ext_Assets_JsDependency))
#10 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(86): Kwf_Assets_ProviderList_Abstract->_setDependen
ciesForDependency(Object(Kwf_Ext_Assets_JsDependency))
#11 C:\OpenServer\domains\kwfapp\vendor\koala-framework\kwf-extjs\Kwf\Ext\Assets
\Provider.php(191): Kwf_Assets_ProviderList_Abstract->findDependency('Ext4.app.E
ventD...')
#12 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(114): Kwf_Ext_Assets_Provider->getDependenciesForDe
pendency(Object(Kwf_Ext_Assets_JsDependency))
#13 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(104): Kwf_Assets_ProviderList_Abstract->getDependen
ciesForDependency(Object(Kwf_Ext_Assets_JsDependency))
#14 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(86): Kwf_Assets_ProviderList_Abstract->_setDependen
ciesForDependency(Object(Kwf_Ext_Assets_JsDependency))
#15 C:\OpenServer\domains\kwfapp\vendor\koala-framework\kwf-extjs\Kwf\Ext\Assets
\Provider.php(191): Kwf_Assets_ProviderList_Abstract->findDependency('Ext4.app.d
omain...')
#16 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(114): Kwf_Ext_Assets_Provider->getDependenciesForDe
pendency(Object(Kwf_Ext_Assets_JsDependency))
#17 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(104): Kwf_Assets_ProviderList_Abstract->getDependen
ciesForDependency(Object(Kwf_Ext_Assets_JsDependency))
#18 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(86): Kwf_Assets_ProviderList_Abstract->_setDependen
ciesForDependency(Object(Kwf_Ext_Assets_JsDependency))
#19 C:\OpenServer\domains\kwfapp\vendor\koala-framework\kwf-extjs\Kwf\Ext\Assets
\Provider.php(191): Kwf_Assets_ProviderList_Abstract->findDependency('Ext4.app.C
ontro...')
#20 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(114): Kwf_Ext_Assets_Provider->getDependenciesForDe
pendency(Object(Kwf_Assets_Dependency_File_Js))
#21 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(104): Kwf_Assets_ProviderList_Abstract->getDependen
ciesForDependency(Object(Kwf_Assets_Dependency_File_Js))
#22 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(86): Kwf_Assets_ProviderList_Abstract->_setDependen
ciesForDependency(Object(Kwf_Assets_Dependency_File_Js))
#23 C:\OpenServer\domains\kwfapp\vendor\koala-framework\kwf-extjs\Kwf\Ext\Assets
\Provider.php(191): Kwf_Assets_ProviderList_Abstract->findDependency('Kwf.Ext4.A
pp.Ma...')
#24 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(114): Kwf_Ext_Assets_Provider->getDependenciesForDe
pendency(Object(Kwf_Assets_Dependency_File_Js))
#25 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(104): Kwf_Assets_ProviderList_Abstract->getDependen
ciesForDependency(Object(Kwf_Assets_Dependency_File_Js))
#26 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(86): Kwf_Assets_ProviderList_Abstract->_setDependen
ciesForDependency(Object(Kwf_Assets_Dependency_File_Js))
#27 C:\OpenServer\domains\kwfapp\vendor\koala-framework\kwf-extjs\Kwf\Ext\Assets
\AclControllerProvider.php(11): Kwf_Assets_ProviderList_Abstract->findDependency
('App.controller....')
#28 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(83): Kwf_Ext_Assets_AclControllerProvider->getDepen
dency('Ext4AclControll...')
#29 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\Provider\Ini.php(35): Kwf_Assets_ProviderList_Abstract->findDependency('Ext4A
clControll...')
#30 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(83): Kwf_Assets_Provider_Ini->getDependency('AdminI
niDep')
#31 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\Provider\IniNoFiles.php(10): Kwf_Assets_ProviderList_Abstract->findDependency
('AdminIniDep')
#32 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\ProviderList\Abstract.php(83): Kwf_Assets_Provider_IniNoFiles->getDependency(
'Admin')
#33 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\Package.php(28): Kwf_Assets_ProviderList_Abstract->findDependency('Admin')
#34 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\Package.php(81): Kwf_Assets_Package->getDependency()
#35 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Asse
ts\Package.php(75): Kwf_Assets_Package->_getFilteredUniqueDependencies('text/jav
ascript')
#36 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Util
\Build\Types\Assets.php(136): Kwf_Assets_Package->getFilteredUniqueDependencies(
'text/javascript')
#37 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Util
\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Assets->_build(Array)
#38 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Util
\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#39 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Cont
roller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#40 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Cont
roller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#41 C:\OpenServer\domains\kwfapp\vendor\koala-framework\zendframework1\library\Z
end\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('in
dexAction')
#42 C:\OpenServer\domains\kwfapp\vendor\koala-framework\zendframework1\library\Z
end\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Obj
ect(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#43 C:\OpenServer\domains\kwfapp\vendor\koala-framework\koala-framework\Kwf\Cont
roller\Front.php(139): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Req
uest_Cli), Object(Kwf_Controller_Response_Http))
#44 C:\OpenServer\domains\kwfapp\bootstrap.php(31): Kwf_Controller_Front->dispat
ch()
#45 {main} [ERROR] (3179ms)
```

**Comment by nsams** [comment] 2015-02-04 09:40
Confirmed. Seems to be a windows issue.

**Comment by nsams** [comment] 2015-02-04 18:03
should be fixed now.

update from git and execute `composer install`

**Closed as completed by nsams** 2015-02-04 18:03 UTC

**Comment by Sogl** [comment] 2015-02-05 01:29
Thanks, now it works. Looks better than 2 version, but so far still very raw.

**Comment by nsams** [comment] 2015-02-05 19:35
Raw? What do you mean by that?

The main difference is how it is implemented - have a look at the code...

**Comment by Sogl** [comment] 2015-02-06 02:22
> Raw? What do you mean by that?

Every second click on customers shows me error "A Server failure occured.":

```
{
  "error": "Not found",
  "exception": [
    "exception 'Kwf_Exception_NotFound' with message 'Not found' in C:\\OpenServer\\domains\\kwf-app-demo\\vendor\\koala-framework\\koala-framework\\Kwf\\Rest\\Controller\\Model.php:130",
    "Stack trace:",
    "#0 C:\\OpenServer\\domains\\kwf-app-demo\\vendor\\koala-framework\\zendframework1\\library\\Zend\\Controller\\Action.php(516): Kwf_Rest_Controller_Model->getAction()",
    "#1 C:\\OpenServer\\domains\\kwf-app-demo\\vendor\\koala-framework\\zendframework1\\library\\Zend\\Controller\\Dispatcher\\Standard.php(308): Zend_Controller_Action->dispatch('getAction')",
    "#2 C:\\OpenServer\\domains\\kwf-app-demo\\vendor\\koala-framework\\zendframework1\\library\\Zend\\Controller\\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))",
    "#3 C:\\OpenServer\\domains\\kwf-app-demo\\vendor\\koala-framework\\koala-framework\\Kwf\\Controller\\Front.php(139): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))",
    "#4 C:\\OpenServer\\domains\\kwf-app-demo\\bootstrap.php(31): Kwf_Controller_Front->dispatch()",
    "#5 {main}"
  ],
  "success": false
}
```

Export to CSV button in the same way:

```
{
  "error": "Not found",
  "exception": [
    "exception 'Kwf_Exception_NotFound' with message 'Not found' in C:\\OpenServer\\domains\\kwf-app-demo\\vendor\\koala-framework\\koala-framework\\Kwf\\Controller\\Action\\Error\\ErrorController.php:15",
    "Stack trace:",
    "#0 C:\\OpenServer\\domains\\kwf-app-demo\\vendor\\koala-framework\\koala-framework\\Kwf\\Controller\\Action.php(33): Kwf_Controller_Action_Error_ErrorController->errorAction()",
    "#1 C:\\OpenServer\\domains\\kwf-app-demo\\vendor\\koala-framework\\zendframework1\\library\\Zend\\Controller\\Dispatcher\\Standard.php(308): Kwf_Controller_Action->dispatch('errorAction')",
    "#2 C:\\OpenServer\\domains\\kwf-app-demo\\vendor\\koala-framework\\zendframework1\\library\\Zend\\Controller\\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))",
    "#3 C:\\OpenServer\\domains\\kwf-app-demo\\vendor\\koala-framework\\koala-framework\\Kwf\\Controller\\Front.php(139): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))",
    "#4 C:\\OpenServer\\domains\\kwf-app-demo\\bootstrap.php(31): Kwf_Controller_Front->dispatch()",
    "#5 {main}"
  ],
  "success": false
}
```

Also I see in url:

```
http://kwf-app-demo/kwf/ext4/members
```

Why this part `/kwf/ext4/` exists?

Besides, the demo is not the same as in 2nd ExtJS version.

p.s. In which step (in percent) is the transition to 4th ExtJS version? Can I help with something?

**Comment by nsams** [comment] 2015-02-06 12:18
what's the url getting called for the errors you get?
probably it's related to this error: https://github.com/vivid-planet/kwf-app-demo/commit/a805435abdeb7a8c6597a2ec3fe3d10649007140, try re-installing everything or manually chainging the picture_id to null.

`/kwf/ext4/ is correct. That acts as point where the corresponding Ext4 MainController is loaded.

Yes, the form doesn't contain all fields, we didn't have time to add all that. We are using ext4 based applications in production already.

**Comment by Sogl** [comment] 2015-02-06 13:25
> what's the url getting called for the errors you get?

`NetworkError: 404 Not Found - http://kwf-app-demo/api/uploads/15596?_dc=1423228567229&id=15596&applicationAssetsVersion=1423099200` in Customers

`POST http://kwf-app-demo/kwf/media/post-back/json-upload 404 Not Found` in CSV export

> `/kwf/ext4/ is correct. That acts as point where the corresponding Ext4 MainController is loaded.

Every controller in ext4 contain this part or index only?

> We are using ext4 based applications in production already.

But why I don't see ext4 branch in koala-framework repository?
Is it so much time to rewrite app from kwf based on ext2 to kwf based on ext4?

**Comment by nsams** [comment] 2015-02-08 17:33
> > what's the url getting called for the errors you get?
> 
> NetworkError: 404 Not Found - http://kwf-app-demo/api/uploads/15596?
> POST http://kwf-app-demo/kwf/media/post-back/json-upload 404 Not Found in CSV export

Ok, as I thought. Please re-install everything (including database)

> Every controller in ext4 contain this part or index only?

It works different than ext2 did. There is no more AutoGrid/AutoForm on the server side. There is only a REST api the JS communicates with. Please have a detailed look at the code - you'll understand what I mean...

> But why I don't see ext4 branch in koala-framework repository?

Because ext4 support is implemented in it's own repository: kwf-extjs - and that uses "standard" koala-framework. In the case of kwf-app-demo ext4 branch this is master currenctly.

> Is it so much time to rewrite app from kwf based on ext2 to kwf based on ext4?

Yes - you have to rewrite everything basically. That's the reason we choose to use Ext4 for new applications only. It's also possible to create a "hybrid" - where you keep old, working code running with ext2 and add new stuff based on ext4.

**Comment by Sogl** [comment] 2015-02-09 05:15
> Ok, as I thought. Please re-install everything (including database)

Broke on build step:

```
c:\OpenServer\domains\kwfapp-ext4>php bootstrap.php build
[ 1/3] building trl...... OK (0ms)
[ 2/3] building events... OK (26ms)
[ 3/3] building assets...
calculating dependencies...
 42% [#########------------] Admin js                                          exception 'Kwf_Exception' with message 'Can't find built dependency for Moxie in vendor/bower_components/moxie' in C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\BowerBuiltFile.php:115
Stack trace:
#0 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_BowerBuiltFile->getDependency('Moxie')
#1 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\AtRequires.php(31): Kwf_Assets_ProviderList_Abstract->findDependency('Moxie')
#2 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(114): Kwf_Assets_Provider_AtRequires->getDependenciesForDependency(Object(Kwf_Assets_Dependency_File_Js))
#3 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(104): Kwf_Assets_ProviderList_Abstract->getDependenciesForDependency(Object(Kwf_Assets_Dependency_File_Js))
#4 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(86): Kwf_Assets_ProviderList_Abstract->_setDependenciesForDependency(Object(Kwf_Assets_Dependency_File_Js))
#5 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\kwf-extjs\Kwf\Ext\Assets\Provider.php(190): Kwf_Assets_ProviderList_Abstract->findDependency('Kwf.Ext4.form.f...')
#6 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(114): Kwf_Ext_Assets_Provider->getDependenciesForDependency(Object(Kwf_Assets_Dependency_File_Js)) #7 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(104): Kwf_Assets_ProviderList_Abstract->getDependenciesForDependency(Object(Kwf_Assets_Dependency_File_Js))
#8 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(86): Kwf_Assets_ProviderList_Abstract->_setDependenciesForDependency(Object(Kwf_Assets_Dependency_File_Js))
#9 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\kwf-extjs\Kwf\Ext\Assets\Provider.php(190): Kwf_Assets_ProviderList_Abstract->findDependency('App.view.member...')
#10 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(114): Kwf_Ext_Assets_Provider->getDependenciesForDependency(Object(Kwf_Assets_Dependency_File_Js))

#11 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(104): Kwf_Assets_ProviderList_Abstract->getDependenciesForDependency(Object(Kwf_Assets_Dependency_File_Js))
#12 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(86): Kwf_Assets_ProviderList_Abstract->_setDependenciesForDependency(Object(Kwf_Assets_Dependency_File_Js))
#13 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\kwf-extjs\Kwf\Ext\Assets\Provider.php(190): Kwf_Assets_ProviderList_Abstract->findDependency('App.view.Member...')
#14 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(114): Kwf_Ext_Assets_Provider->getDependenciesForDependency(Object(Kwf_Assets_Dependency_File_Js))

#15 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(104): Kwf_Assets_ProviderList_Abstract->getDependenciesForDependency(Object(Kwf_Assets_Dependency_File_Js))
#16 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(86): Kwf_Assets_ProviderList_Abstract->_setDependenciesForDependency(Object(Kwf_Assets_Dependency_File_Js))
#17 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\kwf-extjs\Kwf\Ext\Assets\AclControllerProvider.php(11): Kwf_Assets_ProviderList_Abstract->findDependency('App.controller....')
#18 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Ext_Assets_AclControllerProvider->getDependency('Ext4AclControll...')
#19 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\Ini.php(35): Kwf_Assets_ProviderList_Abstract->findDependency('Ext4AclControll...')
#20 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_Ini->getDependency('AdminIniDep')
#21 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Provider\IniNoFiles.php(10): Kwf_Assets_ProviderList_Abstract->findDependency('AdminIniDep')
#22 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\ProviderList\Abstract.php(83): Kwf_Assets_Provider_IniNoFiles->getDependency('Admin')
#23 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Package.php(28): Kwf_Assets_ProviderList_Abstract->findDependency('Admin')
#24 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Package.php(81): Kwf_Assets_Package->getDependency()
#25 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Assets\Package.php(75): Kwf_Assets_Package->_getFilteredUniqueDependencies('text/javascript')
#26 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Assets.php(136): Kwf_Assets_Package->getFilteredUniqueDependencies('text/javascript')
#27 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Assets->_build(Array)
#28 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#29 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#30 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#31 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#32 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#33 C:\OpenServer\domains\kwfapp-ext4\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(139): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#34 C:\OpenServer\domains\kwfapp-ext4\bootstrap.php(31): Kwf_Controller_Front->dispatch()
#35 {main} [ERROR] (746ms)
```

> It's also possible to create a "hybrid" - where you keep old, working code running with ext2 and add new stuff based on ext4.

How you make it possible?

**Comment by nsams** [comment] 2015-02-09 12:02
> Broke on build step:

Seems like bower didn't install moxie correctly. What's the composer update (which runs bower) output?

> > It's also possible to create a "hybrid" - where you keep old, working code running with >> ext2 and add new stuff based on ext4.
> 
> How you make it possible?

You can run AutoForm/AutoGrid based code like you always did. Dependencies need to include both ext versions obviously - but that is not a problem.

**Comment by Sogl** [comment] 2015-02-09 13:27
> Seems like bower didn't install moxie correctly. What's the composer update (which runs bower) output?

```
c:\OpenServer\domains\kwfapp-ext4>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/kwf-modernizr'...

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/koala-framework'...

installing npm dependencies in 'C:\OpenServer\domains\kwfapp-ext4/vendor/koala-framework/kwf-deftjs'...

installing bower dependencies...

c:\OpenServer\domains\kwfapp-ext4>
```

> You can run AutoForm/AutoGrid based code like you always did. Dependencies need to include both ext versions obviously - but that is not a problem.

Need to see. Can you put some code here?

**Comment by nsams** [comment] 2015-02-09 17:27
Ok I also had the problem, that was a merge error in kwf - sorry. please update and `composer install`

I added some code here: https://github.com/vivid-planet/kwf-app-demo/commit/b5efced7767f7cfe73fbb9db25361f478f5313fc

**Comment by Sogl** [comment] 2015-02-10 03:16
> Ok I also had the problem, that was a merge error in kwf - sorry. please update and composer install

Works but put much in console:

```
[I] Adding 'exportCsv' component reference for selector: 'button#exportCsvButton'.
js?v=1423534824 (строка 18)
[I] Adding component selector for: 'button#exportCsvButton'.
js?v=1423534824 (строка 18)
[I] Adding 'click' listener to 'button#exportCsvButton'.
js?v=1423534824 (строка 18)
[I] Adding 'saveButton' component reference for selector: 'button#saveButton'.
js?v=1423534824 (строка 18)
[I] Adding component selector for: 'button#saveButton'.
js?v=1423534824 (строка 18)
[I] Adding 'click' listener to 'button#saveButton'.
js?v=1423534824 (строка 18)
[I] Adding 'deleteButton' component reference for selector: 'button#deleteButton'.
js?v=1423534824 (строка 18)
[I] Adding component selector for: 'button#deleteButton'.
js?v=1423534824 (строка 18)
[I] Adding 'click' listener to 'button#deleteButton'.
js?v=1423534824 (строка 18)
[I] Adding 'deleteButton' component reference for selector: 'button#deleteButton'.
js?v=1423534824 (строка 18)
[I] Adding component selector for: 'button#deleteButton'.
js?v=1423534824 (строка 18)
[I] Adding 'click' listener to 'button#deleteButton'.
js?v=1423534824 (строка 18)
[I] Adding 'memberForm' component reference for selector: '#memberForm'.
js?v=1423534824 (строка 18)
[I] Adding component selector for: '#memberForm'.
js?v=1423534824 (строка 18)
[I] Adding 'membersGrid' component reference for selector: '#membersGrid'.
js?v=1423534824 (строка 18)
[I] Adding component selector for: '#membersGrid'.
js?v=1423534824 (строка 18)
[I] Adding 'membersContactsGrid' component reference for selector: '#membersContactsGrid'.
js?v=1423534824 (строка 18)
[I] Adding component selector for: '#membersContactsGrid'.
```

"Export to CSV" not works:

```
POST http://kwfapp-ext4/kwf/media/post-back/json-upload 401 Access Denied 67ms  
js?v=1423534824 (строка 97)
"NetworkError: 401 Access Denied - http://kwfapp-ext4/kwf/media/post-back/json-upload"
```

> I added some code here: b5efced

Why I can't see this change after `composer update`?

**Comment by nsams** [comment] 2015-02-10 07:33
> Works but put much in console:

That's normal. Yes a bit annoying - but [DeftJS](http://deftjs.org/) is creating that output.

> "Export to CSV" not works:

ah, yes, fixed now. (https://github.com/vivid-planet/kwf-app-demo/commit/ec4bb71d01fde4cbc880677588f6bd6543fa31ce)

> Why I can't see this change after composer update?

because it's a change in kwf-app-demo itself. `git pull` is your friend. `composer update` is for updating vendor libraries. Usually you would do  `git pull` followed by a `composer install`. (https://adamcod.es/2013/03/07/composer-install-vs-composer-update.html)
